# Generated by Django 3.0.5 on 2020-04-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200418_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default=None, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(),
        ),
    ]
