# Generated by Django 3.0.5 on 2020-04-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200419_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shipping',
        ),
    ]
